name: "NixOS Tests"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

      - uses: cachix/cachix-action@v15
        with:
          name: esselius-config
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: nix-community

      - uses: rrbutani/use-nix-shell-action@v1

      - name: Monitoring Auth
        run: nix run .#nixosTests.monitoring-auth